function [ vtcConfigs ] = parametersVTCRun( configs , functionalRuns , f , sliceTypePath )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

    vtcConfigs = struct();
    
    vtcPrefix = fullfile( configs.dataRootSubject,...
                          functionalRuns(f).name,...
                          'PROJECT',...
                          'PROCESSING' );
    
    vtcConfigs.iaName = configs.iaTransf;
    
    vtcConfigs.faName = configs.faTransf;
        
    runName = strsplit(functionalRuns(f).name,'-');
    
    vtcConfigs.fmrName = fullfile( vtcPrefix, ...
        [ configs.filesSignature '_' runName{2} '_' sliceTypePath '_3DMCTS_LTR_THPGLMF2c.fmr' ] );
    
    if configs.ATAL || configs.MTAL
        vtcConfigs.vtcName = fullfile(  configs.dataRootSubject,functionalRuns(f).name,...
            'PROJECT','ANALYSIS' , ...
            [ configs.filesSignature '_' runName{2} '_' sliceTypePath '_3DMCTS_LTR_THPGLMF2c_TAL.vtc' ] );
    else
        vtcConfigs.vtcName = fullfile(  configs.dataRootSubject,functionalRuns(f).name,...
            'PROJECT','ANALYSIS' , ...
            [ configs.filesSignature '_' runName{2} '_' sliceTypePath '_3DMCTS_LTR_THPGLMF2c_NATIVE.vtc' ] );
    end
    
    if configs.IIHC
        
        if configs.ATAL % Automatic TAL
            vtcConfigs.acpcTrfName = configs.acpcTransf;
            vtcConfigs.talTrfName = configs.talTransf;
            vtcConfigs.vmrName = fullfile( configs.dataRootSubject,...
                'anatomical', ...
                'PROJECT', ...
                [ configs.filesSignature '_IIHC_aTAL.vmr' ] );
        elseif configs.MTAL % Manual TAL
            vtcConfigs.acpcTrfName = configs.acpcTransf;
            vtcConfigs.talTrfName = configs.talTransf;
            vtcConfigs.vmrName = fullfile( configs.dataRootSubject,...
                'anatomical', ...
                'PROJECT', ...
                [ configs.filesSignature '_IIHC_TAL.vmr' ] );
        else % None
            vtcConfigs.vmrName = fullfile( configs.dataRootSubject,...
                'anatomical', ...
                'PROJECT', ...
                [ configs.filesSignature '_IIHC.vmr' ] );
        end
        
    else
        if configs.ATAL % Automatic TAL
            vtcConfigs.acpcTrfName = configs.acpcTransf;
            vtcConfigs.talTrfName = configs.talTransf;
            vtcConfigs.vmrName = fullfile( configs.dataRootSubject,...
                'anatomical', ...
                'PROJECT', ...
                [ configs.filesSignature '_aTAL.vmr' ] );
        elseif configs.MTAL % Manual TAL
            vtcConfigs.acpcTrfName = configs.acpcTransf;
            vtcConfigs.talTrfName = configs.talTransf;
            vtcConfigs.vmrName = fullfile( configs.dataRootSubject,...
                'anatomical', ...
                'PROJECT', ...
                [ configs.filesSignature '_TAL.vmr' ] );
        else % None
            vtcConfigs.vmrName = fullfile( configs.dataRootSubject,...
                'anatomical', ...
                'PROJECT', ...
                [ configs.filesSignature '.vmr' ] );
        end
    end  
       
end

