function g_linePlotAverageERA(data_subset, graphTitle, XLabel_str, YLabel_str, xAxisLabels, printGraph)
% example:  g_linePlotAverageERA(data_subset, 'teste', 'XLabel', 'YLabel',{'','',''}, 1)


% varIn
if nargin < 6
    printGraph = 0;
end
    

%% plot dev.

avERA = mean(data_subset,1);
sdERA = std(data_subset,1);

% colors
colorsPerLn = copper(1);

numPnts = size(data_subset,2);

% Create Graph
figure('Units', 'pixels', ...
    'Position', [100 100 1000 600]);

hold on;

%% for each patient


% per run
hData= errorbar( 1:numPnts, avERA, sdERA);

set( hData   , ...
    'Color'           , colorsPerLn, ...
    'LineStyle'       , '-'         , ...
    'LineWidth'       , .5           , ...
    'Marker'          , 'o'         , ...
    'MarkerSize'      , 5           , ...
    'MarkerEdgeColor' , 'none'      , ...
    'MarkerFaceColor' , colorsPerLn );
    



hTitle  = title ( graphTitle );
hXLabel = xlabel( XLabel_str );
hYLabel = ylabel( YLabel_str   );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');

set(gca, ...
    'Box'         , 'off'       , ...
    'TickDir'     , 'out'       , ...
    'TickLength'  , [.02 .02]   , ...
    'XMinorTick'  , 'off'       , ...
    'YMinorTick'  , 'on'        , ...
    'XGrid'       , 'on'        , ...
    'YGrid'       , 'on'        , ...
    'XColor'      , [.3 .3 .3]  , ...
    'YColor'      , [.3 .3 .3]  , ...
    'YTick'       , floor (min (min (avERA) ) ):.2:ceil(max (max (avERA) ) ), ...
    'XTick'       , 1:1:numPnts       , ...
    'XTickLabel'  , xAxisLabels , ...
    'YLim'        , [floor(min (min (avERA) ) ), ceil(max (max (avERA) ) )], ...
    'XLim'        , [1-.3,numPnts+.3],...
    'LineWidth'   , 1           );

set(gcf, 'PaperPositionMode', 'auto');

if printGraph
    eval( ['print -dpng ' graphTitle] )
    close;
end

end

% {'Session #1', 'Session #2', 'Session #3', 'Session #4', 'Session #5'}
% 'XTickLabel'  , {'train', 'neurofeedback #1', 'neurofeedback #2', 'transfer'}, ...
