function [anovatbl] = reapMeasAnovaPerSession(data)
% Repeated measures ANOVA
% per session

PatTags = {'pat_01',...
        'pat_02',...
        'pat_03',...
        'pat_04',...
        'pat_05',...
        'pat_06',...
        'pat_07',...
        'pat_08',...
        'pat_09',...
        'pat_10',...
        'pat_11',...
        'pat_12',...
        'pat_13',...
        'pat_14',...
        'pat_15'};
    
tags = {'patients',...
    'Session_1',...
    'Session_2',...
    'Session_3',...
    'Session_4',...
    'Session_5'};


t_data = table(PatTags',...
    data(:,1),...
    data(:,2),...
    data(:,3),...
    data(:,4),...
    data(:,5),...
    'VariableNames',...
    tags);

t_tags = table([1 2 3 4 5]','VariableNames',{'Sessions'});

rm = fitrm(t_data,'Session_1,Session_2,Session_3,Session_4,Session_5~1','WithinDesign',t_tags);

anovatbl = ranova(rm);


