function [anovatbl] = reapMeasAnovaPerSession(data)
% Repeated measures ANOVA
% per session

for i = 1:size(data,1)
    Tags{i} = ['data_' num2str(i)];
end
    
tags = {'patients',...
    'run_1',...
    'run_2',...
    'run_3',...
    'run_4'};


t_data = table(Tags',...
    data(:,1),...
    data(:,2),...
    data(:,3),...
    data(:,4),...
    'VariableNames',...
    tags);

t_tags = table([1 2 3 4]','VariableNames',{'Runs'});

rm = fitrm(t_data,'run_1,run_2,run_3,run_4~1','WithinDesign',t_tags);

anovatbl = ranova(rm);


